language: objective-c
osx_image: xcode7.2

xcode_workspace: Example/GPXKit.xcworkspace
xcode_scheme: GPXKit
xcode_sdk: iphonesimulator9.2

deploy:
  provider: script
  script:
    - source ~/.rvm/scripts/rvm
    - rvm use default
    - pod trunk push
  on:
    tags: true
