osx_image: xcode8.1
language: objective-c
cache: bundler
rvm:
  - 2.3.1

install:
  - bundle install
  - ./scripts/setup_swiftlint.sh

script:
  - set -o pipefail
  - swiftlint
  - xcodebuild test -workspace Example/TrackKit.xcworkspace -scheme Tests -destination "platform=iOS Simulator,name=iPhone 7"

deploy:
  skip_cleanup: true
  provider: script
  script: 'PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" rvm "$TRAVIS_RUBY_VERSION" do bundle exec pod trunk push'
  on:
    tags: true
    branch: master
