language: objective-c
osx_image: xcode7.2

xcode_workspace: Example/GPXKit.xcworkspace
xcode_scheme: GPXKit-Example
xcode_sdk: iphonesimulator9.2

install: gem install cocoapods
script:
  - pod lib lint
