osx_image: xcode8
language: generic
rvm:
  - 2.2

install:
  - ./install_swiftlint.sh

before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - gem install cocoapods -v '1.1.0.rc2' -N --no-ri --no-rdoc

script:
  - set -o pipefail
  - swiftlint
  - xcodebuild clean test -workspace Example/LogKit.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone 6" -enableCodeCoverage YES | xcpretty

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true
    branch: master
