language: objective-c
osx_image: xcode7.2

xcode_workspace: Example/GPXKit.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator9.2

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true
