osx_image: xcode8
language: objective-c
rvm:
  - '2.2'

before_install:
  - gem install xcpretty -N --no-ri --no-rdoc

install:
  - bundle install
  - ./scripts/setup_swiftlint.sh

script:
  - set -o pipefail
  - swiftlint
  - xcodebuild test -workspace Example/TrackKit.xcworkspace -scheme Tests -destination "platform=iOS Simulator,name=iPhone 7" -enableCodeCoverage YES | xcpretty

deploy:
  skip_cleanup: true
  provider: script
  script: bundle exec pod trunk push
  on:
    tags: true
    branch: master
