language: swift
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "Example/GPXKit.xcworkspace" -scheme "GPXKit-Example" -sdk "iphonesimulator8.1" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
