osx_image: xcode9.3
language: objective-c
cache:
   - bundler
   - cocoapods
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - gem install cocoapods -v '1.5.0' -N --no-ri --no-rdoc
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild test -workspace Example/TrackKit.xcworkspace -scheme Tests -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty

deploy:
  skip_cleanup: true
  provider: script
  script: 'PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" pod trunk push'
  on:
    tags: true
    branch: master
