osx_image: xcode7.2
language: swift

xcode_project: Example/GPXKit.xcworkspace
xcode_scheme: GPXKit-Example

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "Example/GPXKit.xcworkspace" -scheme "GPXKit-Example" -sdk "iphonesimulator9.2" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
